name: flutter_challenge
description: A Flutter project for Banana Software.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^8.0.1
  http: ^0.13.6
  appsize: ^1.2.1
  provider: ^6.0.5
  extended_masked_text: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
